 - project:
     check:
       jobs:
         - validate

 - job:
     name: validate
     description: Validate manifests and scripts syntax
     run: ci/validate.yaml
     nodeset:
       nodes:
         - name: container
           label: zuul-worker-f38
